x = float(input("Enter x:"))
y = float(input("Enter y:"))

print("Sum:", x + y)
print("Subtract:", x - y)
print("Mult:", x * y)
print("Float Division:", x / y)
print("Integer Division:", x // y)
print("Power:", x ** y)
print("Remainder:", x % y)
